import json
import os
import whisper
import yt_dlp
from django.conf import settings
from core.settings import  YDL_OPTS
from google import genai
from google.genai import types
from quizz_app.models import Question


gemini_client = genai.Client(api_key=settings.GEMINI_API_KEY)


def get_prompt(transcript_text):
        prompt = f'''
        Create a quiz based on the following video transcript.

        Requirements:
        - Create 10 multiple-choice questions.
        - Each question must have exactly 4 answer options.
        - Return the answer in the following JSON format:

        {{
        'title': 'Quiz Title',
        'description': 'Brief description',
        'questions': [
            {{
            'question_title': '...',
            'question_options': ['...', '...', '...', '...'],
            'answer': '...'
            }}
        ]
        }}

        Transcript:
        {transcript_text}
        '''
        return prompt
    
def check_content_formatting(quiz_content):
    '''
    Check and correct the formatting of the generated quiz content.

    Args:
        quiz_content (str): The raw quiz content generated by Gemini.
    Returns:
        dict: {'success': True, 'formatted_quiz': {...}} or {'success': False, 'error': '...'}
    '''
    try:
        return json.loads(quiz_content)
    except json.JSONDecodeError:
        '''
        If the model mixes text with JSON → look for JSON part
        '''
        start = quiz_content.find('{')
        end = quiz_content.rfind('}') + 1
        if start != -1 and end != -1:
            return json.loads(quiz_content[start:end])
        else:
            raise ValueError('Gemini output was not valid JSON.')
        
def download_audio_from_url(url, quiz_id):
    
    if not url:
        return {'success': False, 'error': 'The Video URl where not provided.'}
    
    ydl_opts = YDL_OPTS.copy()
    ydl_opts['outtmpl'] = f'media/quiz_{quiz_id}/%(id)s.%(ext)s'
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)
            audio_file_path = ydl.prepare_filename(info_dict)
        return {'success': True, 'file_path': audio_file_path, 'title': info_dict.get('title', 'Unknow Title')}
    except Exception:
        return {'success': False, 'error': 'Failed to download audio from the provided URL.'}
    
def transcription_with_whisper(audio_file_path) :
    '''
    Transcribe an audio file using OpenAI Whisper.

    Args:
        audio_file_path (str): Path to the audio file.
        model_size (str): Whisper model size ('tiny', 'base', 'small', 'medium', 'large').

    Returns:
        dict: {'success': True, 'transcript': '...'} or {'success': False, 'error': '...'}
    '''
    if not os.path.exists(audio_file_path):
        return {'success': False, 'error': 'Audio file does not exist.'}

    try:
        model = whisper.load_model('small')
        result = model.transcribe(audio_file_path, fp16=False)

        transcript_text = result.get('text', '').strip()

        return {'success': True, 'transcript': transcript_text}

    except Exception as e:
        return {'success': False, 'error': f'Whisper transcription failed: {str(e)}'}

def generate_quizes_using_genmini_ai(transcript_text):
    '''
    Generate a quiz based on a video transcript using Gemini.

    Args:
        transcript (str): Video transcript text.
        model (str): Gemini model to use.

    Returns:
        dict: {'success': True, 'quiz': {...}} or {'success': False, 'error': '...'}
    '''
    
    if not transcript_text:
        return {'success': False, 'error': 'Transcript text is empty.', 'questions': []}
    
    try:
        safe_transcript = transcript_text[:12000].replace('\0', '')
        safe_transcript = safe_transcript.replace('{', '{{').replace('}', '}}')
        response = gemini_client.models.generate_content(
            model='gemini-2.5-flash',
            config = types.GenerateContentConfig(
                system_instruction='You are a helpful assistant that generates structured quizzes in JSON format.'),
            contents =  get_prompt(safe_transcript)
        )
        quiz_content = response.text.strip()
        check_content_formatting(quiz_content)
        return {'success': True, 'quiz_content': check_content_formatting(quiz_content)}
    except Exception as e:
        return {'title': 'AI error', 'description':f'Something when wrong during the quiz generation: {str(e)}', 'questions': []}  
    
def generate_quizzes_from_video(quiz):
    '''
        Load audio, transcribe and generate quiz data (modifies the DB).
     Args:
        quiz (Quiz): Quiz instance to update.
        Returns:
        Quiz: Updated Quiz instance with generated questions.
    '''
    result = download_audio_from_url(quiz.video_url, quiz.id)
    if not result['success']:
        return {'success': False, 'error': result['error'], 'questions': []}
    audio_file_path = result['file_path']
    transcription_result = transcription_with_whisper(audio_file_path)
    if not transcription_result['success']:
        return {'success': False, 'error': transcription_result['error'], 'questions': []}
    transcript_text = transcription_result['transcript']
    quiz_data = generate_quizes_using_genmini_ai(transcript_text)
    quiz.title = quiz_data.get('title', 'Generated Quiz')
    quiz.description = quiz_data.get('description', '')
    quiz.save()
    
    for question_data in quiz_data.get('questions', []):
        question = Question(
            quiz=quiz,
            question_title=question_data.get('question_title', ''),
            question_options=question_data.get('question_options', []),
            answer=question_data.get('answer', '')
        )
        question.save()
    return quiz

def generate_quiz_from_youtube(video_url: str, quiz_id=None) -> dict:
    '''
    Full pipeline: YouTube → audio → transcript → Gemini quiz JSON
    '''

    download = download_audio_from_url(video_url, quiz_id)
    if not download['success']:
        return download
    
    print("Audio downloaded to:", download)

    transcript_res = transcription_with_whisper(download['file_path'])
    if not transcript_res['success']:
        return transcript_res

    quiz_res = generate_quizes_using_genmini_ai(transcript_res['transcript'])
    quiz_data = quiz_res.get('quiz_content')
    print(quiz_data)

    return {
        'success': True,
        'quiz': quiz_data,
        'audio_path': video_url,
        'title': download['title'],
    }

